# Generated by Django 4.1 on 2022-10-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_alter_newsmodel_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='article_id',
            new_name='article',
        ),
    ]
